"""
REDDIT-FLOW-NODE — Agent Refiner
==================================
Implements a 3-pass 'Recursive Feedback' loop:

  Pass 1 — Agent A (Proposer):
    Takes the raw user idea and generates a structured Reddit blueprint.

  Pass 2 — Agent B (Critic):
    Reviews the blueprint, identifies weaknesses, and proposes improvements.

  Pass 3 — Final Synthesis:
    Incorporates the critic's feedback into a polished, high-conversion blueprint.

Falls back to deterministic mock responses if no OPENAI_API_KEY is set.
"""

import os
import json
import time
from typing import Optional


# -----------------------------------------------------------------------
# Mock AI responses — used when no API key is available
# -----------------------------------------------------------------------

_MOCK_PROPOSE_TEMPLATE = """
## Proposed Reddit Blueprint [MOCK]

**Original Idea:** {idea}

### Post Type
Self-post (text only)

### Recommended Subreddits
- r/SideProject
- r/Entrepreneur
- r/MachineLearning

### Hook Title (A/B options)
A) "I built {idea} — here's what I learned after 90 days"
B) "Why {idea} might be the next big thing (with data)"

### Post Body Structure
1. **Opening Hook** — Personal story or surprising stat (2 sentences)
2. **Problem Statement** — What pain point does this solve?
3. **The Solution** — Your unique approach (bullet list, max 5 points)
4. **Evidence / Results** — Screenshots, numbers, or testimonials
5. **Call to Action** — "Would love your honest feedback in the comments."

### Best Posting Times
- Tuesday/Thursday 8–10 AM EST
- Saturday 10 AM–12 PM EST

### Engagement Tactics
- Reply to every comment in the first 2 hours
- Cross-post to 1–2 related subreddits after 24 hours
""".strip()

_MOCK_CRITIQUE_TEMPLATE = """
## Critic Review [MOCK]

### Strengths
- Clear subreddit targeting
- Multiple title options reduce A/B risk
- Structured body prevents wall-of-text penalty

### Weaknesses & Recommendations
1. **Missing Keywords** — Add trending keywords like 'automation', 'AI', 'no-code'
   to improve algorithmic visibility.
2. **Flair Strategy** — Many subreddits require/reward specific flairs;
   add a flair recommendation per subreddit.
3. **Hook Specificity** — The hook titles are generic. Use real numbers:
   "I built {idea} and got 3,000 upvotes in 24 hours — here's exactly how."
4. **Comment Seeding** — Prepare 3 thoughtful follow-up comments to post
   as replies to yourself to spark early engagement.

### Revised Title Suggestion
"[CASE STUDY] How I used {idea} to [specific result] — full breakdown"
""".strip()

_MOCK_FINAL_TEMPLATE = """
## ✅ Final Reddit Blueprint [MOCK]

**Refined Idea:** {idea}
**Refinement Passes:** 2 (Propose → Critique → Synthesize)

---

### 🎯 Target Subreddits (with flairs)
| Subreddit | Flair | Timing |
|-----------|-------|--------|
| r/SideProject | Show HN | Tue 9 AM EST |
| r/Entrepreneur | Case Study | Thu 8 AM EST |
| r/MachineLearning | Discussion | Sat 11 AM EST |

### 🏷️ Final Title (High-Conversion)
"[CASE STUDY] I built {idea} — here's the exact system I used to [result]"

### 📝 Body Structure
1. **Hook** (2 sentences with a number or surprising fact)
2. **Problem** (1 paragraph — be vulnerable, not salesy)
3. **Solution Deep-Dive** (5 bullet points with specifics)
4. **Proof** (embed image/chart if allowed; otherwise link to GitHub/Loom)
5. **Lessons Learned** (3 bullet points — adds authenticity)
6. **CTA** (1 gentle question to drive comments)

### 💬 Seed Comments (post as replies to yourself)
1. "Happy to share the codebase if anyone wants to build on this."
2. "The biggest mistake I made early on was X — would love to hear if others faced this."
3. "For anyone asking about Y, here's a quick breakdown: [link or explanation]"

### ⏱️ Rate Limit Safe Schedule
- Post #1 → wait 48 hours minimum before Post #2
- Use Reddit Flow Node's built-in scheduler to queue posts safely

---
*Generated by REDDIT-FLOW-NODE Agent Refiner (Mock Mode)*
""".strip()


# -----------------------------------------------------------------------
# AgentRefiner
# -----------------------------------------------------------------------

class AgentRefiner:
    """
    Recursive feedback agent that refines a raw idea into a production-quality
    Reddit blueprint through a 3-pass critique loop.
    """

    MODEL = "gpt-4o-mini"

    def __init__(self):
        self._api_key: Optional[str] = os.environ.get("OPENAI_API_KEY", "").strip()
        self._use_mock = not bool(self._api_key)

        if not self._use_mock:
            try:
                import litellm  # type: ignore
                self._litellm = litellm
            except ImportError:
                self._use_mock = True

        from core.llm_factory import ProviderFactory
        self._factory = ProviderFactory

    # -------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------

    def refine(self, raw_idea: str, provider_name: str = "litellm", max_iterations: int = 1) -> dict:
        """
        Run the full 3-pass refinement pipeline.

        Args:
            raw_idea: The user's unstructured idea or prompt.
            provider_name: 'litellm', 'groq', or 'ollama'.
            max_iterations: Number of critique→revise cycles (default 1).

        Returns:
            A dict with 'proposed', 'critique', 'final', 'mode', 'iterations'.
        """
        start = time.monotonic()

        if self._use_mock:
            result = self._mock_pipeline(raw_idea, max_iterations)
        else:
            result = self._live_pipeline(raw_idea, provider_name, max_iterations)

        result["duration_seconds"] = round(time.monotonic() - start, 2)
        return result

    # -------------------------------------------------------------------
    # Mock pipeline
    # -------------------------------------------------------------------

    def _mock_pipeline(self, raw_idea: str, iterations: int) -> dict:
        """Return deterministic mock results for all three passes."""
        time.sleep(0.5)  # Simulate processing delay
        return {
            "mode": "mock",
            "iterations": iterations,
            "raw_idea": raw_idea,
            "proposed": _MOCK_PROPOSE_TEMPLATE.format(idea=raw_idea),
            "critique": _MOCK_CRITIQUE_TEMPLATE.format(idea=raw_idea),
            "final": _MOCK_FINAL_TEMPLATE.format(idea=raw_idea),
            "tokens_used": 150
        }

    # -------------------------------------------------------------------
    # Live pipeline (LiteLLM → OpenAI)
    # -------------------------------------------------------------------

    def _live_pipeline(self, raw_idea: str, provider_name: str, iterations: int) -> dict:
        total_tokens = 0
        provider = self._factory.get_provider(provider_name)
        
        def _call(messages):
            nonlocal total_tokens
            res = provider.chat_generate(messages)
            total_tokens += res.get("tokens", 0)
            return res.get("content", "")

        proposed = _call(self._build_propose_prompt(raw_idea))

        critique = proposed
        for _ in range(iterations):
            critique_text = _call(self._build_critique_prompt(raw_idea, critique))
            critique = critique_text

        final = _call(self._build_synthesis_prompt(raw_idea, proposed, critique))

        return {
            "mode": "live",
            "provider_matched": provider_name,
            "iterations": iterations,
            "raw_idea": raw_idea,
            "proposed": proposed,
            "critique": critique,
            "final": final,
            "tokens_used": total_tokens
        }

    # -------------------------------------------------------------------
    # Prompt builders
    # -------------------------------------------------------------------

    @staticmethod
    def _build_propose_prompt(raw_idea: str) -> list[dict]:
        return [
            {
                "role": "system",
                "content": (
                    "You are a professional Reddit growth strategist and prompt engineer. "
                    "Your task is to take a raw idea and produce a STRUCTURED, "
                    "high-conversion Reddit content blueprint. Be specific, data-driven, "
                    "and format your output in clear Markdown sections."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Raw idea: {raw_idea}\n\n"
                    "Generate a complete Reddit content blueprint including: "
                    "target subreddits, 2 title options (A/B), full body structure, "
                    "best posting times, and engagement tactics."
                ),
            },
        ]

    @staticmethod
    def _build_critique_prompt(raw_idea: str, proposed: str) -> list[dict]:
        return [
            {
                "role": "system",
                "content": (
                    "You are a sharp, skeptical Reddit strategy critic. "
                    "Your job is to review a content blueprint and identify every "
                    "weakness, vague claim, or missed opportunity. "
                    "Be brutally honest and provide SPECIFIC improvements."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Original idea: {raw_idea}\n\n"
                    f"Blueprint to review:\n{proposed}\n\n"
                    "List all weaknesses and provide improved alternatives for each."
                ),
            },
        ]

    @staticmethod
    def _build_synthesis_prompt(raw_idea: str, proposed: str, critique: str) -> list[dict]:
        return [
            {
                "role": "system",
                "content": (
                    "You are a master Reddit content architect. "
                    "Synthesize a proposer's blueprint and a critic's review into a "
                    "single, polished, final blueprint that addresses all weaknesses "
                    "and maximizes engagement potential. Output clean Markdown."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Original idea: {raw_idea}\n\n"
                    f"Proposed blueprint:\n{proposed}\n\n"
                    f"Critic's review:\n{critique}\n\n"
                    "Produce the final, optimized Reddit blueprint."
                ),
            },
        ]
